# name: ci
# on: [push]
# jobs:
#   test:
#     steps:
#     name: Checkout
#     uses: actions/checkout@v3
    
#     name: Parallel Test
#     # https://github.com/bahmutov/cypress-workflows
#     uses: bahmutov/cypress-workflows/.github/workflows/split.yml@v2
#     with:
#       nE2E: 3\\


name: ci
'on':
  - push
jobs:
  test:
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Parallel Test
        uses: bahmutov/cypress-workflows/.github/workflows/split.yml@v2
    with: 
    nE2E: 3
