name: Parallel End to End tests
on: push
jobs:
  strategy:
  fail-fast: false
  matrix:
    containers: [1, 2, 3]
steps:
  - name: Run split Cypress tests 🧪
    uses: cypress-io/github-action@v5
    # pass the machine index and the total number
    env:
      SPLIT: ${{ strategy.job-total }}
      SPLIT_INDEX: ${{ strategy.job-index }}
      
      - name: artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with: 
          name: cypress-videos
          path: cypress/videos

          